runtime: python39
instance_class: F1

env_variables:
  FLASK_ENV: "production"
  FLASK_APP: "src/backend/app.py"

handlers:
  # Serve static files from the frontend build directory
  - url: /static
    static_dir: src/frontend/build/static
    secure: always

  # Serve the frontend application
  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg))$
    static_files: src/frontend/build/\1
    upload: src/frontend/build/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg)$
    secure: always

  # Serve the main application
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 2
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50 